### ISSUE TITLE
Zabbix 6 auditlog

### ISSUE THREAD

**Issue by rjorgenson-ns** [OpensourceICTSolutions/zabbix-mysql-partitioning-perl#8]
In Zabbix 6 the auditlog was reworked and auditlog_details no longer exists. I have commented this line out of the script for now and it is partitioning fine but I'm unsure if it is leaving junk in the auditlog and if that query should be reworked somehow for the new auditlog table.

**Comment by larcorba** [comment]
Hi Rjorgenson-ns,

Thanks for opening the issue! We know about it and will release a modified script once the Zabbix 6 release is out.

**Comment by larcorba** [comment]
auditlog_details has been removed in it's entiry and the rest of Auditlog is still maintained correctly. Commenting the line is exactly enough to resolve the issue. Resolved in: #10 

Thanks for opening the issue!
